/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PC_H_RPCGEN
#define _PC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PC_PROG 0x20000001
#define PC_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define consume 1
extern  enum clnt_stat consume_1(void *, char *, CLIENT *);
extern  bool_t consume_1_svc(void *, char *, struct svc_req *);
#define produce 2
extern  enum clnt_stat produce_1(void *, char *, CLIENT *);
extern  bool_t produce_1_svc(void *, char *, struct svc_req *);
extern int pc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
int init_pc();

#else /* K&R C */
#define consume 1
extern  enum clnt_stat consume_1();
extern  bool_t consume_1_svc();
#define produce 2
extern  enum clnt_stat produce_1();
extern  bool_t produce_1_svc();
extern int pc_prog_1_freeresult ();
int init_pc();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PC_H_RPCGEN */
