/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "pc.h"
#include <string.h>
#include <unistd.h>
#include <stdlib.h>

void
pc_prog_consume(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	char *produce_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(getpid());
	while (1) {
		sleep(rand() % 3 + 1);

		retval_1 = consume_1((void*)&produce_1_arg, &result_1, clnt);
		if (retval_1 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
		}
		printf("get %c\n", result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void
pc_prog_produce(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	char result_1;
	char *produce_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, PC_PROG, PC_VERSION, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	srand(getpid());
	while (1) {
		sleep(rand() % 3 + 1);

		retval_1 = produce_1((void*)&produce_1_arg, &result_1, clnt);
		if (retval_1 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
		}
		printf("put %c\n", result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host pc_type\n", argv[0]);
		printf ("pc_type = 1 - consumer\n");
		printf ("pc_type = 2 - producer\n");
		exit (1);
	}
	if (strcmp(argv[2], "1") != 0 && strcmp(argv[2], "2") != 0) {
		printf ("usage: %s server_host pc_type\n", argv[0]);
		printf ("pc_type = 1 - consumer\n");
		printf ("pc_type = 2 - producer\n");
		exit (1);
	}
	host = argv[1];
	if (strcmp(argv[2], "1") == 0) {
		pc_prog_consume (host);
	}
	
	else {
        pc_prog_produce (host);
    }
exit (0);
}
