/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "pc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
consume_1(void *argp, char *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, consume,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_char, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
produce_1(void *argp, char *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, produce,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_char, (caddr_t) clnt_res,
		TIMEOUT));
}
