/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "pc.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

pthread_t p_thread;
pthread_attr_t attr;

// У всех функций нет аргументов, создан для rpc
union argument_t {
	int fill;
};
void*
serv_request(void *data)
{
	struct thr_data
	{
		struct svc_req *rqstp;
		SVCXPRT *transp;
		union argument_t argument;
	} *ptr_data;
	union argument_t argument;
	union {
		char consume_1_res;
		char produce_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);
	ptr_data = (struct thr_data *) data;
	struct svc_req *rqstp = ptr_data->rqstp;
	register SVCXPRT *transp = ptr_data->transp;
	argument = ptr_data->argument;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return NULL;
	case consume:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))consume_1_svc;
		break;
	case produce:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))produce_1_svc;
		break;
	default:
		svcerr_noproc (transp);
		return NULL;
	}

	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!pc_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return NULL;
}

static void
pc_prog_1(struct svc_req *rqstp, register SVCXPRT *transp) {
	xdrproc_t _xdr_argument;

	// выделение структуры, для передачи обработчику в отдельном потоке
	struct data_str
	{
		struct svc_req *rqstp;
		SVCXPRT *transp;
		union argument_t argument;
	} *data_ptr=(struct data_str*)malloc(sizeof(struct data_str));
	if (data_ptr == NULL) {
		fprintf (stderr, "%s", "unable to allocate memory.");
        exit(1);
    }
	// получение аргументов вызова
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return ;
		break;
	case produce:
		_xdr_argument = (xdrproc_t) xdr_void;
		break;
	case consume:
		_xdr_argument = (xdrproc_t) xdr_void;
		break;
	default:
		svcerr_noproc (transp);
		return ;
		break;
	}
	// svc_getargs не потокобезопасна, поэтому, если аргументы есть, их получение происходит на этом этапе
	memset ((char *)&data_ptr->argument, 0, sizeof (data_ptr->argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &data_ptr->argument)) {
		svcerr_decode (transp);
		return;
	}
	data_ptr->rqstp = rqstp;
	data_ptr->transp = transp;

	// Создание detached потока с обработчиком
	pthread_attr_init(&attr);
	pthread_attr_setdetachstate(&attr,PTHREAD_CREATE_DETACHED);
	pthread_create(&p_thread,&attr,serv_request,(void *)data_ptr);
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	// Инициализация семафоров и буфера
	if (init_pc() != 0) {
		fprintf (stderr, "%s", "unable to initialize.");
        exit(1);
	}
	pmap_unset (PC_PROG, PC_VERSION);
	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PC_PROG, PC_VERSION, pc_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PC_PROG, PC_VERSION, udp).");
		exit(1);
	}
	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PC_PROG, PC_VERSION, pc_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PC_PROG, PC_VERSION, tcp).");
		exit(1);
	}
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
