/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "bakery.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct BAKERY_CALCULATOR *
get_number_1(struct BAKERY_CALCULATOR *argp, CLIENT *clnt)
{
	static struct BAKERY_CALCULATOR clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, get_number,
		(xdrproc_t) xdr_BAKERY_CALCULATOR, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY_CALCULATOR, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct BAKERY_CALCULATOR *
perform_1(struct BAKERY_CALCULATOR *argp, CLIENT *clnt)
{
	static struct BAKERY_CALCULATOR clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, perform,
		(xdrproc_t) xdr_BAKERY_CALCULATOR, (caddr_t) argp,
		(xdrproc_t) xdr_BAKERY_CALCULATOR, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
