/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BAKERY_H_RPCGEN
#define _BAKERY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3
#define PROC_COUNT 1000
#define TIMEOUT_SECONDS 30
#define SERVER_TIMEOUT_SECONDS 1

struct BAKERY_CALCULATOR {
	int index;
	int pid;
	int num;
	int op;
	float arg1;
	float arg2;
	float result;
};
typedef struct BAKERY_CALCULATOR BAKERY_CALCULATOR;

#define BAKERY_PROG 0x20000001
#define BAKERY_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_number 1
extern  struct BAKERY_CALCULATOR * get_number_1(struct BAKERY_CALCULATOR *, CLIENT *);
extern  struct BAKERY_CALCULATOR * get_number_1_svc(struct BAKERY_CALCULATOR *, struct svc_req *);
#define perform 2
extern  struct BAKERY_CALCULATOR * perform_1(struct BAKERY_CALCULATOR *, CLIENT *);
extern  struct BAKERY_CALCULATOR * perform_1_svc(struct BAKERY_CALCULATOR *, struct svc_req *);
extern int bakery_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_number 1
extern  struct BAKERY_CALCULATOR * get_number_1();
extern  struct BAKERY_CALCULATOR * get_number_1_svc();
#define perform 2
extern  struct BAKERY_CALCULATOR * perform_1();
extern  struct BAKERY_CALCULATOR * perform_1_svc();
extern int bakery_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_BAKERY_CALCULATOR (XDR *, BAKERY_CALCULATOR*);

#else /* K&R C */
extern bool_t xdr_BAKERY_CALCULATOR ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BAKERY_H_RPCGEN */
