/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

pthread_t p_thread;
pthread_attr_t attr;

union argument_t {
		struct BAKERY_CALCULATOR get_number_1_arg;
		struct BAKERY_CALCULATOR perform_1_arg;
};


static void*
bakery_prog_serve(void *data)
{
	struct thr_data
	{
	struct svc_req *rqstp;
	SVCXPRT *transp;
	union argument_t argument;
	} *ptr_data;
	union argument_t argument;
	union {
		struct BAKERY_CALCULATOR get_number_1_res;
		struct BAKERY_CALCULATOR perform_1_res;
	} result;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *,  struct svc_req *);

	ptr_data = (struct thr_data *) data;
	struct svc_req *rqstp = ptr_data->rqstp;
	register SVCXPRT *transp = ptr_data->transp;
	argument = ptr_data->argument;

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return NULL;

	case get_number:
		_xdr_argument = (xdrproc_t) xdr_BAKERY_CALCULATOR;

		_xdr_result = (xdrproc_t) xdr_BAKERY_CALCULATOR;
		local = (bool_t (*) (char *, void *,  struct svc_req *))get_number_1_svc;
		break;

	case perform:
		_xdr_argument = (xdrproc_t) xdr_BAKERY_CALCULATOR;
		_xdr_result = (xdrproc_t) xdr_BAKERY_CALCULATOR;
		local = (bool_t (*) (char *, void *,  struct svc_req *))perform_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return NULL;
	}
	// memset ((char *)&argument, 0, sizeof (argument));
	// if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
	// 	svcerr_decode (transp);
	// 	return NULL;
	// }
	// printf("start %d\n", argument.get_number_1_arg.num);
	
	bool_t retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		// printf("end %d\n", argument.get_number_1_arg.num);
		svcerr_systemerr (transp);
	}
	
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!bakery_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return NULL;
}

static void
bakery_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	struct data_str
	{
		struct svc_req *rqstp;
		SVCXPRT *transp;
		union argument_t argument;
	} *data_ptr=(struct data_str*)malloc(sizeof(struct data_str));
	if (data_ptr == NULL) {
		fprintf (stderr, "%s", "unable to allocate memory.");
        exit(1);
    }
	data_ptr->rqstp = rqstp;
	data_ptr->transp = transp;
	memset ((char *)&data_ptr->argument, 0, sizeof (data_ptr->argument));
	if (!svc_getargs (transp, (xdrproc_t) xdr_BAKERY_CALCULATOR, (caddr_t) &data_ptr->argument)) {
		svcerr_decode (transp);
		return;
	}

	pthread_attr_init(&attr);
	pthread_attr_setdetachstate(&attr,PTHREAD_CREATE_DETACHED);
	pthread_create(&p_thread,&attr,bakery_prog_serve,(void *)data_ptr);
	// printf("thread %d\n", data_ptr->argument.get_number_1_arg.index);
	usleep(300);
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (BAKERY_PROG, BAKERY_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, BAKERY_PROG, BAKERY_VER, bakery_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BAKERY_PROG, BAKERY_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, BAKERY_PROG, BAKERY_VER, bakery_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BAKERY_PROG, BAKERY_VER, tcp).");
		exit(1);
	}

	if (init_server_mutex()) {
		fprintf(stderr, "Unable to initialize server mutex.\n");
        exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
