/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <errno.h>
#include <sys/wait.h>
#include <unistd.h>


void
bakery_prog_1(char *host, int index)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	struct BAKERY_CALCULATOR result_1;
	struct BAKERY_CALCULATOR  get_number_1_arg;
	enum clnt_stat retval_2;
	struct BAKERY_CALCULATOR result_2;
	struct BAKERY_CALCULATOR  perform_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(getpid());
	
	get_number_1_arg.index = index;
	get_number_1_arg.op = rand() % 4;
	get_number_1_arg.arg1 = rand() % 100;
	get_number_1_arg.arg2 = rand() % 100 + 1;
	get_number_1_arg.pid = getpid();

	// usleep(350 * index);

	retval_1 = get_number_1(&get_number_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}
	printf("pid %d: got number %d\n", result_1.pid, result_1.index, result_1.num);

	perform_1_arg = result_1;


	usleep(350 *index);

	// printf("start perform at %d\n", result_1.num);
	retval_2 = perform_1(&perform_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}
	char op;
	switch (result_2.op)
	{
	case ADD:
		op = '+';
		break;
	case SUB:
	    op = '-';
	    break;
	case MUL:
	    op = '*';
	    break;
	case DIV:
		op = '/';
	default:
		printf("error: invalid operation\n");
		exit(1);
		break;
	}

	printf("pid %d: %f %c %f = %f\n", result_2.pid, result_2.arg1, op, result_2.arg2, result_2.result);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	printf("%d\n", PROC_COUNT);

	pid_t childpid[PROC_COUNT];
    for (int i = 0; i < PROC_COUNT; i++) {
        childpid[i] = fork();
        if (childpid[i] == -1) {
            perror("fork");
            return 1;
        } else if (childpid[i] == 0) {
            bakery_prog_1(host, i);
            return 0;
        }

    }

	pid_t cpid = 0;
    int wstatus = 0;
    while (cpid != -1) {
        cpid = wait(&wstatus);
        if (cpid == -1) {
            if (errno == EINTR) {
                cpid=0;
            } else if (errno != ECHILD) {
                printf("Error: wait %d\n", wstatus);
                exit(EXIT_FAILURE);
            }
		}
    }

exit (0);
}
